### ISSUE TITLE
Define an official alias

### ISSUE THREAD

**Issue by MatthieuBizien** [szymonmaszke/torchlayers#1]
Most Python numerical libraires define an official alias, like np for numpy, because the full name is long and noisy. It's important to discourage the bad practice of `import *`, and to increase code reusability. In pytorch, we mainly use nn that makes the job.

I propose tl, as it's short, clear, and to my knowledge not used in numerical python.

What do you think about using `import torchlayers as tl` in all your examples?

**Comment by szymonmaszke** [comment]
Thanks for your input! Personally I'm not the biggest fan of aliases as those do not aid readability IMO (besides a few well recognized ones like `np` or `tf`).

PyTorch itself doesn't create those aliases (or rather does so inconsistently), see [beginners guide](https://pytorch.org/tutorials/beginner/pytorch_with_examples.html) which uses fully qualified names (`import torch` and `torch.nn.Module`).

Also, `torchlayers` provides only limited support for `from torchlayers import *` (it would export `[build, infer]` functions and `[Lambda, Concatenate, Reshape]` layers), nothing related to shape inference could be used this way so I don't think this practice would happen in this case.

Leaving it open for now, if there is enough support for your case and more people feel `torchlayers` needs an official alias I will reconsider.

**Comment by devanshuDesai** [comment]
I concur with OP. I was just about to create a new issue on this exact topic. AFAIK PyTorch is the only major Python tool that doesn't have an official alias. All major tools like Pandas and Numpy use an alias. PyTorch can get away with it as `torch` is maybe just short enough but I find it very difficult to believe that as this library gains traction most people will spell out the full `torchlayers`. Not everybody has autocompletion set up in their favorite code editor and non-native English speakers might find it tad frustrating to spell out the full `torchlayers` everytime. 

Another counterpoint would be that even PyTorch uses aliases for longer names like `import torch.nn.functional as F`. I am also in favor of replacing all `import torchlayers` with `import torchlayers as tl`. Those who want to spell out the whole thing can still choose to ignore it just like purists who spell out the full `numpy.reshape` for example. If more people are in favor of this, I don't mind refactoring the documentation and making a pull request.

**Comment by szymonmaszke** [comment]
@devanshuDesai your arguments convinced me so you can go ahead and refactor `README.md` and `/docs` and I will happily merge (I agree `tl` is a good alias). Please open a new PR if you follow through with it, closing for now.
