### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by pengzhangzhi** [szymonmaszke/torchlayers#10]
Hi!
I implement the code `pip install --user torchlayers` in anaconda prompt 

Then I get the error as follow:

`ERROR: Could not find a version that satisfies the requirement torchlayers (from versions: none)
ERROR: No matching distribution found for torchlayers`

Would you please help me out? 

If you need more detailed information,please tell me! 

I appreciate it!
![image](https://user-images.githubusercontent.com/59241275/95343389-0ccc8980-08eb-11eb-95c6-10c754492df4.png)

**Comment by szymonmaszke** [comment]
What is your `python` version? Currently only `3.7+` is supported.

**Comment by pengzhangzhi** [comment]
Thanks! Problem solved!
