### ISSUE TITLE
torchlayers gives error in Google Colab 

### ISSUE THREAD

**Issue by pranjalchaubey** [szymonmaszke/torchlayers#5]
I was trying out the basic example given in the repo description in Google Colab and it is throwing an error. 
```
---------------------------------------------------------------------------

AttributeError                            Traceback (most recent call last)

<ipython-input-8-d2b2c25b5f66> in <module>()
      1 model = torch.nn.Sequential(
----> 2     tl.Conv(64),  # specify ONLY out_channels
      3     torch.nn.ReLU(),  # use torch.nn wherever you wish
      4     tl.BatchNorm(),  # BatchNormNd inferred from input
      5     tl.Conv(128),  # Default kernel_size equal to 3

AttributeError: module 'torchlayers' has no attribute 'Conv'
```

Here's the code, 
![torchlayers](https://user-images.githubusercontent.com/23052833/78510396-69bb7b80-77b2-11ea-9ebe-d89a26bea1fa.png)

**Comment by pranjalchaubey** [comment]
I am getting the same error on the Paperspace cloud as well.

**Comment by szymonmaszke** [comment]
Answer was given in #4 - `torchlayers` needs python `3.7` which introduces module `__getattr__` (main requirement of this project), hence `colab` cannot be currently supported without workaround (it provides Python `3.6.9` runtime).

Removed `torchlayers-0.1.0` version though as it was put up by mistake (with Python 3.6 support specified, sorry for confusion).

Could you try again with `Paperspace` and check which Python version is provided as I've never used their service? If the version is `<3.7` you could probably try [this link](https://medium.com/quark-works/ml-cloud-computing-part-2-connecting-pycharm-to-paperspace-f2272b2d528) and set up `anaconda` environment with Python 3.7, in this case `torchlayers` should run out of the box.

**Comment by pranjalchaubey** [comment]
Thanks for the reply @szymonmaszke! 
I will try and see if I can run the library on Paperspace.

**Comment by szymonmaszke** [comment]
@pranjalchaubey please do and report if any error unrelated to Python version occurs, thanks. Closing for now, reopen if needed or further questions arise.
