### ISSUE TITLE
AttributeError: module 'torchlayers' has no attribute 'Linear'

### ISSUE THREAD

**Issue by soulhi-vz** [szymonmaszke/torchlayers#7]
Hi,
Got the error below:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-32-33b501e736c0> in <module>
----> 1 print(Autoencoder())

<ipython-input-30-e7bbee6595f8> in __init__(self)
      8             nn.Conv1d(out_channels,in_channels,kernel_size),
      9             nn.ReLU(True),
---> 10             torchlayers.Linear(2))

AttributeError: module 'torchlayers' has no attribute 'Linear'

 
![image](https://user-images.githubusercontent.com/61634050/79474248-293ed780-7fd4-11ea-9a37-8f6c2f16c837.png)

<img width="596" alt="torchlayers" src="https://user-images.githubusercontent.com/61634050/79474550-8b97d800-7fd4-11ea-9e0c-20a88ef7f8f3.PNG">

**Comment by szymonmaszke** [comment]
Your Python version is `3.6`, see #4 and #5 (Python `3.7` or greater is required). Removed bugged wheels for nightly version where Python `3.6` was allowed, thanks for the catch.

**Comment by soulhi-vz** [comment]
Thanks Szymon for the prompt answer !!
